name: Frontend CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # Enables caching node_modules

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run build process
      - name: Build project
        run: npm run build

      # Step 5: Run tests (if present)
      - name: Run tests
        run: npm test --if-present

      # Optional: Upload production-ready build artifacts
      - name: Upload production build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build/
